import Link from "next/link"
import styles from '@/styles/Index.module.css'
import {useState} from "react";
import {useFormInput} from "@/utils/hooks";


export default function Index() {
    const [show, setShow] = useState(false);
    const login = useFormInput('');
    const password = useFormInput('');

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);

    const handleAuth = () => {
        if (login.value === process.env.login && password.value === process.env.password) {
            sessionStorage && sessionStorage.setItem("accessToken", "123");
            setShow(false);
        }
    }

    const handleExit = () => {
        sessionStorage && sessionStorage.removeItem("accessToken");
        window.location.reload();
    }
    return (
        <>
            {/*<Head>*/}
            {/*  <title>Create Next App</title>*/}
            {/*  <meta name="description" content="Generated by create next app" />*/}
            {/*  <meta name="viewport" content="width=device-width, initial-scale=1" />*/}
            {/*  <link rel="icon" href="/favicon.ico" />*/}
            {/*</Head>*/}
            {/*<main className={styles.main}>*/}
            {/*  <div className={styles.description}>*/}
            {/*    <p>*/}
            {/*      Get started by editing&nbsp;*/}
            {/*      <code className={styles.code}>src/pages/index.js</code>*/}
            {/*    </p>*/}
            {/*    <div>*/}
            {/*      <a*/}
            {/*        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*        target="_blank"*/}
            {/*        rel="noopener noreferrer"*/}
            {/*      >*/}
            {/*        By{' '}*/}
            {/*        <Image*/}
            {/*          src="/vercel.svg"*/}
            {/*          alt="Vercel Logo"*/}
            {/*          className={styles.vercelLogo}*/}
            {/*          width={100}*/}
            {/*          height={24}*/}
            {/*          priority*/}
            {/*        />*/}
            {/*      </a>*/}
            {/*    </div>*/}
            {/*  </div>*/}

            {/*  <div className={styles.center}>*/}
            {/*    <Image*/}
            {/*      className={styles.logo}*/}
            {/*      src="/next.svg"*/}
            {/*      alt="Next.js Logo"*/}
            {/*      width={180}*/}
            {/*      height={37}*/}
            {/*      priority*/}
            {/*    />*/}
            {/*    <div className={styles.thirteen}>*/}
            {/*      <Image*/}
            {/*        src="/thirteen.svg"*/}
            {/*        alt="13"*/}
            {/*        width={40}*/}
            {/*        height={31}*/}
            {/*        priority*/}
            {/*      />*/}
            {/*    </div>*/}
            {/*  </div>*/}

            {/*  <div className={styles.grid}>*/}
            {/*    <a*/}
            {/*      href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*      className={styles.card}*/}
            {/*      target="_blank"*/}
            {/*      rel="noopener noreferrer"*/}
            {/*    >*/}
            {/*      <h2 className={inter.className}>*/}
            {/*        Docs <span>-&gt;</span>*/}
            {/*      </h2>*/}
            {/*      <p className={inter.className}>*/}
            {/*        Find in-depth information about Next.js features and&nbsp;API.*/}
            {/*      </p>*/}
            {/*    </a>*/}

            {/*    <a*/}
            {/*      href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*      className={styles.card}*/}
            {/*      target="_blank"*/}
            {/*      rel="noopener noreferrer"*/}
            {/*    >*/}
            {/*      <h2 className={inter.className}>*/}
            {/*        Learn <span>-&gt;</span>*/}
            {/*      </h2>*/}
            {/*      <p className={inter.className}>*/}
            {/*        Learn about Next.js in an interactive course with&nbsp;quizzes!*/}
            {/*      </p>*/}
            {/*    </a>*/}

            {/*    <a*/}
            {/*      href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*      className={styles.card}*/}
            {/*      target="_blank"*/}
            {/*      rel="noopener noreferrer"*/}
            {/*    >*/}
            {/*      <h2 className={inter.className}>*/}
            {/*        Templates <span>-&gt;</span>*/}
            {/*      </h2>*/}
            {/*      <p className={inter.className}>*/}
            {/*        Discover and deploy boilerplate example Next.js&nbsp;projects.*/}
            {/*      </p>*/}
            {/*    </a>*/}

            {/*    <a*/}
            {/*      href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*      className={styles.card}*/}
            {/*      target="_blank"*/}
            {/*      rel="noopener noreferrer"*/}
            {/*    >*/}
            {/*      <h2 className={inter.className}>*/}
            {/*        Deploy <span>-&gt;</span>*/}
            {/*      </h2>*/}
            {/*      <p className={inter.className}>*/}
            {/*        Instantly deploy your Next.js site to a shareable URL*/}
            {/*        with&nbsp;Vercel.*/}
            {/*      </p>*/}
            {/*    </a>*/}
            {/*  </div>*/}
            {/*</main>*/}

            <div style={{
                display: "flex",
                flexDirection: "column",
                width: "100vw",
                height: "100vh",
                background: "#fafbff"
            }}>

                <div className={styles.gridNav}>
                    <Link href={"/algorithms"}>
                        <div className={styles.gridNavItem}>Алгоритмы и их Q-детерминанты</div>
                    </Link>
                    <div className={styles.gridNavItem}>Сравнение алгоритмов</div>
                    <div className={styles.gridNavItem}>Сервис аппроксимации</div>
                    <div className={styles.gridNavItem}>Документация</div>
                    <div className={styles.gridNavItem}>Публикации</div>
                    {(typeof window !== 'undefined') && sessionStorage.getItem("accessToken") ?
                        <div className={styles.gridNavItem} onClick={handleExit}>Выйти</div>
                        :
                        <div className={styles.gridNavItem} onClick={handleShow}>Авторизация</div>
                    }
                    {(typeof window !== 'undefined') && sessionStorage.getItem("accessToken") &&
                    <Link href={"/admin"}>
                        <div className={styles.gridNavItem}>Управление</div>
                    </Link>}
                </div>


                {show && <div className={styles.back}>
                    <div className={styles.modal}>
                        <input value={login.value}
                               onChange={login.onChange}
                               placeholder="Enter Name En"/>

                        <input value={password.value}
                               onChange={password.onChange}
                               placeholder="Enter Name Ru"
                               type={"password"}/>


                        <div>
                            <button className="primaryButton"
                                    onClick={handleAuth}
                                    disabled={login.value === '' || password.value === ''}>Save
                            </button>
                            <button className="secondaryButton" onClick={handleClose}>Cancel</button>
                        </div>
                    </div>
                </div>}

            </div>


        </>
    )
}
